version: 2.1
defaults: &defaults
  docker:
    - image: circleci/node:13.8.0

# Here the start of the exercise from the course:
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: npm i
      - save_cache:
          key: "npm_packages"
          paths:
            - "/src/node_modules"
          key: 
      - run: npm run lint

  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - "npm_packages"
      - run: npm i
      - run: npm run test

  analyze:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - "npm_packages"
      - run: npm audit

# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  ci_pipeline_exercise:
    # Run the welcome/run job in its own container
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test
